---
- name: Apply netplan config
  become: true
  command: netplan apply
  listen: netplan apply config

- name: Generate netplan config
  become: true
  command: netplan generate
  listen: netplan generate config
  notify: netplan apply config
