# handlers file
---
- name: apply netplan config
  ansible.builtin.command: >
    netplan apply
  listen: netplan apply config

- name: generate netplan config
  ansible.builtin.command: >
    netplan generate
  listen: netplan generate config
  notify: netplan apply config
