# handlers file
---
- name: generate netplan config  # noqa no-changed-when
  ansible.builtin.command: >
    netplan generate

- name: apply netplan config  # noqa no-changed-when
  ansible.builtin.command: >
    netplan apply
